# Generated by Django 3.0.1 on 2021-10-26 13:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GameMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mod', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sort_term_memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.BooleanField()),
                ('two', models.BooleanField()),
                ('three', models.BooleanField()),
                ('four', models.BooleanField()),
                ('five', models.BooleanField()),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.GameMod')),
            ],
        ),
        migrations.CreateModel(
            name='store_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=10)),
                ('time', models.PositiveIntegerField()),
                ('ans', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('day', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='headshot/')),
            ],
        ),
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TimeStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_one', models.CharField(max_length=30)),
                ('time_two', models.CharField(max_length=30)),
                ('time_three', models.CharField(max_length=30)),
                ('time_four', models.CharField(max_length=30)),
                ('time_five', models.CharField(max_length=30)),
                ('sort_term_memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.Sort_term_memory')),
            ],
        ),
        migrations.AddField(
            model_name='gamemod',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.UserName'),
        ),
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_rate', models.IntegerField()),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.GameMod')),
            ],
        ),
    ]
