# Generated by Django 3.0.1 on 2021-10-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attention',
            options={'ordering': ['add_time']},
        ),
        migrations.AlterModelOptions(
            name='sort_term_memory',
            options={'ordering': ['add_time']},
        ),
    ]
