# Generated by Django 3.0.1 on 2021-11-23 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_auto_20211026_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attention',
            options={'ordering': ['-add_time']},
        ),
        migrations.AlterModelOptions(
            name='sort_term_memory',
            options={'ordering': ['-add_time']},
        ),
        migrations.RemoveField(
            model_name='sort_term_memory',
            name='five',
        ),
        migrations.RemoveField(
            model_name='sort_term_memory',
            name='four',
        ),
        migrations.RemoveField(
            model_name='timestore',
            name='time_five',
        ),
        migrations.RemoveField(
            model_name='timestore',
            name='time_four',
        ),
        migrations.AlterField(
            model_name='gamemod',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.Userdata'),
        ),
    ]
