# Generated by Django 3.0.1 on 2021-11-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0005_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientation',
            name='costTime',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
