# Generated by Django 3.0.1 on 2021-11-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0006_orientation_costtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sort_term_memory',
            old_name='one',
            new_name='correct_rate',
        ),
        migrations.AddField(
            model_name='sort_term_memory',
            name='costTime',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TimeStore',
        ),
    ]
